### ISSUE TITLE
Joint-Genotyping

### ISSUE THREAD

**Issue by jjfarrell** [spiralgenetics/biograph#12]
Is biograph able to joint-genotype across a set of project samples? How does one create a project level VCF for analyses with biographies?

**Comment by ACEnglish** [comment]
Hello,

Yes, BioGraph can create a squared off project-level VCF. The procedure hasn't been fully optimized/productionized but is still relatively simple to follow.

First,  single sample VCFs  and BioGraphs are created using the `biograph full_pipeline` command. [link](https://github.com/spiralgenetics/biograph/wiki/full_pipeline)

Second, VCFs are merged. The simplest thing to do is to use `bcftools merge -f x -m none` on the per-sample VCFs.

At this point, you could just run this VCF through `biograph squareoff` per-sample. This command is undocumented in the wiki, so see the `--help` for details. This command re-runs `biograph coverage` on the multi-sample VCF which builds a graph-reference from the variants and generates coverage from a sample's BioGraph file, then runs a `gt_classifier` which is specifically tailored to project-level VCF creation and fills in the FORMAT fields (e.g. GT/DP). 

This `squareoff` procedure needs to be run for every sample. Once you a VCF for each sample where they contain squared-off (filled in) genotypes, you simply re-run `bcftools merge -f x -m none` on the new VCFs and you'll have a project level VCF.

Now, between merging the VCFs and running squareoff, is where you have opportunities to improve/speed-up creation of your pVCF. In the above described procedure, every variant is preserved, which creates a much larger graph-reference. The larger the reference the slower the `biograph coverage` command. So you want to try to pre-filter potential false-positive variants. 

The simplest manipulation is to only preserve variants which are PASS. 

Another highly recommended step is to run `truvari collapse` [link](https://github.com/ACEnglish/truvari/wiki/collapse) which attempts to merge redundant SV representations. This can reduce the number of entries in your VCF (i.e. simplify the graph-reference). [preprint](https://www.biorxiv.org/content/10.1101/2022.02.21.481353v1) 

If you're feeling adventurous, you can use `truvari anno density` [link](https://github.com/ACEnglish/truvari/wiki/anno#truvari-anno-density) to identify regions where there's an abnormally high number of variants, which may represent a lower quality reference region (which is difficult for BioGraph to build a graph-reference over) or limitations of the sequencing (e.g. low-mappability region for short-reads).

One note of caution: while you want to attempt to aggressively remove false-positives from your vcf to simplify the graph-reference and improve runtime, removing true-positives has an outsized effect. This is because the graph-reference created by BioGraph needs to have the full haplotype represented in order to accurately apply coverage. For example, if there is a SNP in high LD and just a few base-pairs up-stream of a DEL, removing the SNP will lose the ability for `biograph coverage` to recreate the exact haplotype needed to generate coverage over the DEL. Therefore, removing this example SNP also loses its neighboring DEL. So just don't go too crazy filtering by doing something like removing all variants <50bp because you're only interested in the >=50bp SV results.

Let me know if you have any more questions and I'll be happy to answer them.

Have a great day,
~/Adam
